using System;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ArchitecturalDecisionRecords
{
    public class AdrSyntaxExpression
    {
        public static SyntaxTrivia Instance()
        {
            return SyntaxFactory.Trivia(SyntaxFactory.DocumentationCommentTrivia(SyntaxKind.SingleLineDocumentationCommentTrivia,
                SyntaxFactory.SingletonList<XmlNodeSyntax>
                    (
                        SyntaxFactory.XmlExampleElement
                        (
                            SyntaxFactory.XmlText()
                            .WithTextTokens
                            (
                                SyntaxFactory.TokenList
                                (
                                    SyntaxFactory.XmlTextNewLine
                                    (
                                        SyntaxFactory.TriviaList(),
                                        Environment.NewLine,
                                        Environment.NewLine,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                            ),
                            SyntaxFactory.XmlExampleElement()
                            .WithStartTag
                            (
                                SyntaxFactory.XmlElementStartTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("useCase")
                                    )
                                )
                                .WithLessThanToken
                                (
                                    SyntaxFactory.Token
                                    (
                                        SyntaxFactory.TriviaList
                                        (
                                            SyntaxFactory.DocumentationCommentExterior("/// ")
                                        ),
                                        SyntaxKind.LessThanToken,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            )
                            .WithEndTag
                            (
                                SyntaxFactory.XmlElementEndTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("useCase")
                                    )
                                )
                                .WithLessThanSlashToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.LessThanSlashToken)
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            ),
                            SyntaxFactory.XmlText()
                            .WithTextTokens
                            (
                                SyntaxFactory.TokenList
                                (
                                    SyntaxFactory.XmlTextNewLine
                                    (
                                        SyntaxFactory.TriviaList(),
                                        Environment.NewLine,
                                        Environment.NewLine,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                            ),
                            SyntaxFactory.XmlExampleElement()
                            .WithStartTag
                            (
                                SyntaxFactory.XmlElementStartTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("concernBeingAddressed")
                                    )
                                )
                                .WithLessThanToken
                                (
                                    SyntaxFactory.Token
                                    (
                                        SyntaxFactory.TriviaList
                                        (
                                            SyntaxFactory.DocumentationCommentExterior("/// ")
                                        ),
                                        SyntaxKind.LessThanToken,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            )
                            .WithEndTag
                            (
                                SyntaxFactory.XmlElementEndTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("concernBeingAddressed")
                                    )
                                )
                                .WithLessThanSlashToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.LessThanSlashToken)
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            ),
                            SyntaxFactory.XmlText()
                            .WithTextTokens
                            (
                                SyntaxFactory.TokenList
                                (
                                    SyntaxFactory.XmlTextNewLine
                                    (
                                        SyntaxFactory.TriviaList(),
                                        Environment.NewLine,
                                        Environment.NewLine,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                            ),
                            SyntaxFactory.XmlExampleElement()
                            .WithStartTag
                            (
                                SyntaxFactory.XmlElementStartTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("agreedApproach")
                                    )
                                )
                                .WithLessThanToken
                                (
                                    SyntaxFactory.Token
                                    (
                                        SyntaxFactory.TriviaList
                                        (
                                            SyntaxFactory.DocumentationCommentExterior("/// ")
                                        ),
                                        SyntaxKind.LessThanToken,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            )
                            .WithEndTag
                            (
                                SyntaxFactory.XmlElementEndTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("agreedApproach")
                                    )
                                )
                                .WithLessThanSlashToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.LessThanSlashToken)
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            ),
                            SyntaxFactory.XmlText()
                            .WithTextTokens
                            (
                                SyntaxFactory.TokenList
                                (
                                    SyntaxFactory.XmlTextNewLine
                                    (
                                        SyntaxFactory.TriviaList(),
                                        Environment.NewLine,
                                        Environment.NewLine,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                            ),
                            SyntaxFactory.XmlExampleElement()
                            .WithStartTag
                            (
                                SyntaxFactory.XmlElementStartTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("acceptedDownside")
                                    )
                                )
                                .WithLessThanToken
                                (
                                    SyntaxFactory.Token
                                    (
                                        SyntaxFactory.TriviaList
                                        (
                                            SyntaxFactory.DocumentationCommentExterior("/// ")
                                        ),
                                        SyntaxKind.LessThanToken,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            )
                            .WithEndTag
                            (
                                SyntaxFactory.XmlElementEndTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("acceptedDownside")
                                    )
                                )
                                .WithLessThanSlashToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.LessThanSlashToken)
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            ),
                            SyntaxFactory.XmlText()
                            .WithTextTokens
                            (
                                SyntaxFactory.TokenList
                                (
                                    SyntaxFactory.XmlTextNewLine
                                    (
                                        SyntaxFactory.TriviaList(),
                                        Environment.NewLine,
                                        Environment.NewLine,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                            ),
                            SyntaxFactory.XmlExampleElement()
                            .WithStartTag
                            (
                                SyntaxFactory.XmlElementStartTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("otherOptionConsidered")
                                    )
                                )
                                .WithLessThanToken
                                (
                                    SyntaxFactory.Token
                                    (
                                        SyntaxFactory.TriviaList
                                        (
                                            SyntaxFactory.DocumentationCommentExterior("/// ")
                                        ),
                                        SyntaxKind.LessThanToken,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            )
                            .WithEndTag
                            (
                                SyntaxFactory.XmlElementEndTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("otherOptionConsidered")
                                    )
                                )
                                .WithLessThanSlashToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.LessThanSlashToken)
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            ),
                            SyntaxFactory.XmlText()
                            .WithTextTokens
                            (
                                SyntaxFactory.TokenList
                                (
                                    SyntaxFactory.XmlTextNewLine
                                    (
                                        SyntaxFactory.TriviaList(),
                                        Environment.NewLine,
                                        Environment.NewLine,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                            ),
                            SyntaxFactory.XmlExampleElement()
                            .WithStartTag
                            (
                                SyntaxFactory.XmlElementStartTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("otherOptionConsidered")
                                    )
                                )
                                .WithLessThanToken
                                (
                                    SyntaxFactory.Token
                                    (
                                        SyntaxFactory.TriviaList
                                        (
                                            SyntaxFactory.DocumentationCommentExterior("/// ")
                                        ),
                                        SyntaxKind.LessThanToken,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            )
                            .WithEndTag
                            (
                                SyntaxFactory.XmlElementEndTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("otherOptionConsidered")
                                    )
                                )
                                .WithLessThanSlashToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.LessThanSlashToken)
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            ),
                            SyntaxFactory.XmlText()
                            .WithTextTokens
                            (
                                SyntaxFactory.TokenList
                                (
                                    SyntaxFactory.XmlTextNewLine
                                    (
                                        SyntaxFactory.TriviaList(),
                                        Environment.NewLine,
                                        Environment.NewLine,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                            ),
                            SyntaxFactory.XmlExampleElement()
                            .WithStartTag
                            (
                                SyntaxFactory.XmlElementStartTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("engineerSignOff")
                                    )
                                )
                                .WithLessThanToken
                                (
                                    SyntaxFactory.Token
                                    (
                                        SyntaxFactory.TriviaList
                                        (
                                            SyntaxFactory.DocumentationCommentExterior("/// ")
                                        ),
                                        SyntaxKind.LessThanToken,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            )
                            .WithEndTag
                            (
                                SyntaxFactory.XmlElementEndTag
                                (
                                    SyntaxFactory.XmlName
                                    (
                                        SyntaxFactory.Identifier("engineerSignOff")
                                    )
                                )
                                .WithLessThanSlashToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.LessThanSlashToken)
                                )
                                .WithGreaterThanToken
                                (
                                    SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                                )
                            ),
                            SyntaxFactory.XmlText()
                            .WithTextTokens
                            (
                                SyntaxFactory.TokenList
                                (
                                    SyntaxFactory.XmlTextNewLine
                                    (
                                        SyntaxFactory.TriviaList(),
                                        Environment.NewLine,
                                        Environment.NewLine,
                                        SyntaxFactory.TriviaList()
                                    )
                                )
                            )
                        )
                        .WithStartTag
                        (
                            SyntaxFactory.XmlElementStartTag
                            (
                                SyntaxFactory.XmlName
                                (
                                    SyntaxFactory.Identifier("adr")
                                )
                            )
                            .WithLessThanToken
                            (
                                SyntaxFactory.Token
                                (
                                    SyntaxFactory.TriviaList
                                    (
                                        SyntaxFactory.DocumentationCommentExterior("/// ")
                                    ),
                                    SyntaxKind.LessThanToken,
                                    SyntaxFactory.TriviaList()
                                )
                            )
                            .WithGreaterThanToken
                            (
                                SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                            )
                        )
                        .WithEndTag
                        (
                            SyntaxFactory.XmlElementEndTag
                            (
                                SyntaxFactory.XmlName
                                (
                                    SyntaxFactory.Identifier("adr")
                                )
                            )
                            .WithLessThanSlashToken
                            (
                                SyntaxFactory.Token
                                (
                                    SyntaxFactory.TriviaList
                                    (
                                        SyntaxFactory.DocumentationCommentExterior("/// ")
                                    ),
                                    SyntaxKind.LessThanSlashToken,
                                    SyntaxFactory.TriviaList()
                                )
                            )
                            .WithGreaterThanToken
                            (
                                SyntaxFactory.Token(SyntaxKind.GreaterThanToken)
                            )
                        )
                    )
                ).WithEndOfComment
                (
                    SyntaxFactory.Token(SyntaxKind.EndOfDocumentationCommentToken)
                ));

        }
    }
}
